In [2]:
import pandas as pd
import numpy as np
data=pd.read_csv("titanic_data.csv")
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [67]:
colsdrop=["PassengerId","Name","Ticket","Cabin","Fare"]
d1=data.drop(colsdrop,axis=1)
d1.head()

Survived  Pclass     Sex   Age  SibSp  Parch Embarked
0         0       3    male  22.0      1      0        S
1         1       1  female  38.0      1      0        C
2         1       3  female  26.0      0      0        S
3         1       1  female  35.0      1      0        S
4         0       3    male  35.0      0      0        S

In [68]:
mean=d1["Age"].mean()
mean

29.69911764705882

In [69]:
std=d1["Age"].std()
std

14.526497332334044

In [70]:
random=d1["Age"].isnull().sum()

In [71]:
random

177

In [72]:
randomvalues=np.random.randint(low=mean-std,high=mean+std,size=random)

In [73]:
randomvalues

array([42, 17, 40, 40, 26, 41, 16, 19, 37, 17, 42, 30, 23, 24, 36, 40, 16,
       27, 40, 41, 43, 26, 22, 20, 36, 29, 20, 19, 30, 41, 23, 39, 30, 18,
       19, 20, 32, 40, 41, 15, 41, 42, 25, 22, 20, 42, 22, 40, 32, 39, 37,
       36, 27, 21, 23, 16, 22, 26, 15, 33, 18, 25, 17, 27, 22, 28, 17, 29,
       25, 23, 17, 25, 33, 24, 37, 39, 27, 32, 17, 21, 25, 33, 17, 29, 35,
       18, 17, 30, 29, 36, 16, 19, 16, 18, 29, 42, 15, 20, 39, 20, 38, 34,
       25, 39, 28, 27, 39, 35, 30, 28, 15, 16, 17, 36, 15, 34, 40, 23, 43,
       43, 29, 23, 42, 39, 15, 20, 36, 41, 22, 36, 39, 43, 15, 34, 19, 27,
       22, 18, 32, 35, 43, 22, 38, 29, 20, 35, 36, 24, 16, 23, 32, 42, 20,
       40, 37, 18, 30, 34, 17, 22, 32, 39, 32, 26, 40, 15, 28, 37, 37, 28,
       33, 30, 22, 25, 18, 27, 26])

In [74]:
a=d1["Age"].copy()
a[np.isnan(a)]=random
d1["Age"]=a


In [75]:
d1["Age"].isnull().sum()

0

In [76]:
d1["Embarked"].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [77]:
d1["Embarked"]=d1["Embarked"].fillna("S")

In [78]:
d1["Embarked"].isnull().sum()

0

# Changing categorical to numerical

In [79]:
d1.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

In [80]:
gender={"male":1,"female":0}
d1["Sex"]=d1["Sex"].map(gender)
d1["Sex"].head()

0    1
1    0
2    0
3    0
4    1
Name: Sex, dtype: int64

In [81]:
ports={"S":0,"C":1,"Q":2}
d1["Embarked"]=d1["Embarked"].map(ports)
d1["Embarked"].head()

0    0
1    1
2    0
3    0
4    0
Name: Embarked, dtype: int64

In [82]:
d1.head()

Survived  Pclass  Sex   Age  SibSp  Parch  Embarked
0         0       3    1  22.0      1      0         0
1         1       1    0  38.0      1      0         1
2         1       3    0  26.0      0      0         0
3         1       1    0  35.0      1      0         0
4         0       3    1  35.0      0      0         0

In [83]:
d1.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Embarked    0
dtype: int64

# Splitting Data

In [84]:
x=d1.loc[:,d1.columns!="Survived"]
x.head()

Pclass  Sex   Age  SibSp  Parch  Embarked
0       3    1  22.0      1      0         0
1       1    0  38.0      1      0         1
2       3    0  26.0      0      0         0
3       1    0  35.0      1      0         0
4       3    1  35.0      0      0         0

In [86]:
y=d1["Survived"]
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [87]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.45)
x_train.head()

Pclass  Sex    Age  SibSp  Parch  Embarked
659       1    1   58.0      0      2         1
434       1    1   50.0      1      0         0
739       3    1  177.0      0      0         0
67        3    1   19.0      0      0         0
513       1    0   54.0      1      0         1

#Scaling 

In [92]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [93]:
x_train

array([[-1.58022661,  0.74535599, -0.02253939, -0.48388063,  2.22696073,
         0.97700214],
       [-1.58022661,  0.74535599, -0.15485597,  0.44958988, -0.47071729,
        -0.57228928],
       [ 0.83195731,  0.74535599,  1.9456698 , -0.48388063, -0.47071729,
        -0.57228928],
       ...,
       [-1.58022661,  0.74535599, -0.25409341,  1.38306038, -0.47071729,
         2.52629356],
       [-1.58022661, -1.34164079,  1.9456698 , -0.48388063, -0.47071729,
         0.97700214],
       [-1.58022661, -1.34164079, -0.58488487, -0.48388063, -0.47071729,
         0.97700214]])

In [94]:
x_test

array([[-0.36366666, -1.37291372, -0.1749218 ,  0.41392463,  1.80183267,
        -0.56479579],
       [-1.54927911, -1.37291372, -0.6928435 ,  0.41392463, -0.48105801,
         1.04146742],
       [-1.54927911,  0.72837789,  1.98030078, -0.46429641, -0.48105801,
         1.04146742],
       ...,
       [-1.54927911,  0.72837789,  1.98030078, -0.46429641, -0.48105801,
        -0.56479579],
       [-1.54927911, -1.37291372, -0.30857901, -0.46429641, -0.48105801,
        -0.56479579],
       [-1.54927911,  0.72837789, -0.37540762,  0.41392463,  1.80183267,
        -0.56479579]])

# Model

In [95]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC

In [103]:
lr=LogisticRegression()
knn=KNeighborsClassifier(5)
dtc=DecisionTreeClassifier()
sv=SVC(kernel="sigmoid")

In [104]:
lr.fit(x_train,y_train)
knn.fit(x_train,y_train)
dtc.fit(x_train,y_train)
sv.fit(x_train,y_train)

SVC(kernel='sigmoid')

# Predict

In [105]:
lrp=lr.predict(x_test)
knnp=knn.predict(x_test)
dtcp=dtc.predict(x_test)
svp=sv.predict(x_test)

# Accuracy

In [107]:
from sklearn.metrics import accuracy_score
log=accuracy_score(y_test,lrp)
knn=accuracy_score(y_test,knnp)
dtc=accuracy_score(y_test,dtcp)
sv=accuracy_score(y_test,svp)

In [108]:
print("logistic regrssion accuracy: ",round(log*100,2))
print("knn accuracy: ",round(knn*100,2))
print("dtc accuracy: ",round(dtc*100,2))
print("sv accuracy: ",round(sv*100,2))

logistic regrssion accuracy:  78.8
knn accuracy:  76.06
dtc accuracy:  77.81
sv accuracy:  67.08
